CREATE TABLE IF NOT EXISTS users (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(16) NOT NULL,
  last_name VARCHAR(16) NOT NULL,
  username VARCHAR(16) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  telephone INT(9) NOT NULL,
  password VARCHAR(255) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender ENUM('WOMAN', 'MAN', 'OTHER') NOT NULL,
  description TEXT NOT NULL,
  photo VARCHAR(255) NOT NULL,
  is_verified BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS advertisement (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  isVisible BOOLEAN NOT NULL,
  title VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS accommodation (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rooms INT NOT NULL,
  beds INT NOT NULL,
  pricePerDay DECIMAL(10,2) NOT NULL,
  pricePerMonth DECIMAL(10,2) NOT NULL,
  description TEXT NOT NULL,
  latitud VARCHAR(50) NOT NULL UNIQUE,
  longitud VARCHAR(50) NOT NULL UNIQUE,
  availability VARCHAR(100) NOT NULL,
  students INT NOT NULL,
  wifi BOOLEAN NOT NULL,
  isEasyParking BOOLEAN NOT NULL,
  advertisementId INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (advertisementId) REFERENCES advertisement(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS booking (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  link VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS owner (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  experienceYears INT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS student (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  isSmoker BOOLEAN NOT NULL,
  academic_career VARCHAR(255) NOT NULL,
  hobbies VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bookingStudent (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bookingDate DATE NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  studentId INT(4) UNSIGNED NOT NULL,
  bookingId INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (studentId) REFERENCES student(id) ON DELETE CASCADE,
  FOREIGN KEY (bookingId) REFERENCES booking(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comment (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CommentDate DATE NOT NULL,
  text TEXT NOT NULL,
  rating INT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS message (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MessageDate DATE NOT NULL,
  text TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_comments (
  user_id INT(4) UNSIGNED NOT NULL,
  comment_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (comment_id) REFERENCES comment(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, comment_id)
) ENGINE=InnoDB;
