SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS comments, bookings, booking_students, accommodations, advertisements, students, owners, users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS users (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(16) NOT NULL,
  last_name VARCHAR(16) NOT NULL,
  username VARCHAR(16) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  telephone VARCHAR(15) NOT NULL,
  password VARCHAR(255) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender ENUM('WOMAN', 'MAN', 'OTHER') NOT NULL,
  description TEXT NOT NULL,
  photo VARCHAR(255) NOT NULL,
  is_verified BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS owners (
  id INT(4) UNSIGNED NOT NULL PRIMARY KEY,
  experienceYears INT NOT NULL,
  FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS students (
  id INT(4) UNSIGNED NOT NULL PRIMARY KEY,
  is_smoker BOOLEAN NOT NULL,
  academic_career VARCHAR(255) NOT NULL,
  hobbies VARCHAR(255) NOT NULL,
  FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS advertisements (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  is_visible BOOLEAN NOT NULL,
  title VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS accommodations (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rooms INT NOT NULL,
  beds INT NOT NULL,
  price_per_day DECIMAL(10,2) NOT NULL,
  price_per_month DECIMAL(10,2) NOT NULL,
  description TEXT NOT NULL,
  latitud VARCHAR(50) NOT NULL UNIQUE,
  longitud VARCHAR(50) NOT NULL UNIQUE,
  availability VARCHAR(100) NOT NULL,
  students INT NOT NULL,
  wifi BOOLEAN NOT NULL,
  is_easy_parking BOOLEAN NOT NULL,
  advertisement_id INT(4) UNSIGNED NOT NULL,
  owner_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (advertisement_id) REFERENCES advertisements(id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  link VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  advertisement_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (advertisement_id) REFERENCES advertisements(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS booking_students (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  booking_date DATE NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  student_id INT(4) UNSIGNED NOT NULL,
  booking_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comments (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  comment_date DATE NOT NULL,
  text TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  accommodation_id INT(4) UNSIGNED DEFAULT NULL,
  user_id INT(4) UNSIGNED DEFAULT NULL,
  student_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (accommodation_id) REFERENCES accommodations(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS messages (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  message_date DATE NOT NULL,
  text TEXT NOT NULL,
  sender_id INT(4) UNSIGNED NOT NULL,
  receiver_id INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

